version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directories:
      - /services/api
      - /services/ingestion
      - /services/workers
      - /services/ner_parser
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /services/api
      - /services/ingestion
      - /services/workers
      - /services/ner_parser
    schedule:
      interval: weekly
